-- EcoSync Database Schema
-- Created for local development environment

-- =====================================================
-- Countries Table
-- =====================================================
CREATE TABLE IF NOT EXISTS countries (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '국가 ID',
    code VARCHAR(2) NOT NULL UNIQUE COMMENT '국가 코드 (ISO 3166-1 alpha-2)',
    name VARCHAR(100) NOT NULL COMMENT '국가명',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    INDEX idx_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='국가 정보';

-- =====================================================
-- Indicators Table
-- =====================================================
CREATE TABLE IF NOT EXISTS indicators (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '지표 ID',
    name VARCHAR(100) NOT NULL UNIQUE COMMENT '지표명',
    description VARCHAR(500) COMMENT '지표 설명',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='환경/경제 지표';

-- =====================================================
-- Stocks Table
-- =====================================================
CREATE TABLE IF NOT EXISTS stocks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '데이터 ID',
    country_id BIGINT NOT NULL COMMENT '국가 ID',
    indicator_id BIGINT NOT NULL COMMENT '지표 ID',
    value DECIMAL(15, 4) NOT NULL COMMENT '지표 값',
    stock_date DATE NOT NULL COMMENT '데이터 기준 일자',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE CASCADE,
    FOREIGN KEY (indicator_id) REFERENCES indicators(id) ON DELETE CASCADE,
    UNIQUE KEY uk_country_indicator_date (country_id, indicator_id, stock_date),
    INDEX idx_stock_date (stock_date),
    INDEX idx_country_id (country_id),
    INDEX idx_indicator_id (indicator_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='국가별 지표 데이터';

-- =====================================================
-- Subscriptions Table
-- =====================================================
CREATE TABLE IF NOT EXISTS subscriptions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '구독 ID',
    user_id BIGINT NOT NULL COMMENT '사용자 ID',
    country_id BIGINT NOT NULL COMMENT '국가 ID',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE CASCADE,
    UNIQUE KEY uk_user_country (user_id, country_id),
    INDEX idx_user_id (user_id),
    INDEX idx_country_id (country_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자 구독 정보';

-- =====================================================
-- SPRING_BATCH Tables (for Batch Processing)
-- =====================================================
CREATE TABLE IF NOT EXISTS BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID BIGINT NOT NULL,
    VERSION BIGINT,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL,
    CONSTRAINT BATCH_JOB_INSTANCE_PK PRIMARY KEY (JOB_INSTANCE_ID),
    CONSTRAINT BATCH_JOB_INSTANCE_UN UNIQUE (JOB_NAME, JOB_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Spring Batch Job Instance';

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    VERSION BIGINT,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME DATETIME(6) NOT NULL,
    START_TIME DATETIME(6),
    END_TIME DATETIME(6),
    STATUS VARCHAR(10),
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED DATETIME(6),
    CONSTRAINT BATCH_JOB_EXECUTION_PK PRIMARY KEY (JOB_EXECUTION_ID),
    CONSTRAINT BATCH_JOB_EXECUTION_FK FOREIGN KEY (JOB_INSTANCE_ID) REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Spring Batch Job Execution';

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT LONGTEXT,
    CONSTRAINT BATCH_JOB_EXECUTION_CONTEXT_PK PRIMARY KEY (JOB_EXECUTION_ID),
    CONSTRAINT BATCH_JOB_EXECUTION_CONTEXT_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Spring Batch Job Execution Context';

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID BIGINT NOT NULL,
    VERSION BIGINT NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    CREATE_TIME DATETIME(6) NOT NULL,
    START_TIME DATETIME(6),
    END_TIME DATETIME(6),
    STATUS VARCHAR(10),
    COMMIT_COUNT BIGINT,
    READ_COUNT BIGINT,
    FILTER_COUNT BIGINT,
    WRITE_COUNT BIGINT,
    READ_SKIP_COUNT BIGINT,
    WRITE_SKIP_COUNT BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT BIGINT,
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED DATETIME(6),
    CONSTRAINT BATCH_STEP_EXECUTION_PK PRIMARY KEY (STEP_EXECUTION_ID),
    CONSTRAINT BATCH_STEP_EXECUTION_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Spring Batch Step Execution';

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID BIGINT NOT NULL,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT LONGTEXT,
    CONSTRAINT BATCH_STEP_EXECUTION_CONTEXT_PK PRIMARY KEY (STEP_EXECUTION_ID),
    CONSTRAINT BATCH_STEP_EXECUTION_CONTEXT_FK FOREIGN KEY (STEP_EXECUTION_ID) REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Spring Batch Step Execution Context';
